### ISSUE TITLE
Unable to use new account

### ISSUE THREAD

**Issue by ItachiSan** [TelepathyQt/telepathy-morse#32] opened 2016-09-13 11:56 UTC
As in title: with latest version of _telepathy-morse_, the initial login (the one with the verification code) doesn't work.
Previously, _Empathy_ showed a dialog asking for a password (the initial PIN code), after which worked properly.
Right now, this doesn't happen.
#### Expected
- Add a new account
- Insert PIN received from Telegram
- Chat
#### What happens
- Add a new account
- Never received the PIN code
#### Setup

ArchLinux, with latest Empathy and telepathy-morse package.
telepathy-morse is built from latest sources, using this PKGBUILD: https://aur.archlinux.org/packages/telepathy-morse-git/

**Comment by Kaffeine** [comment] 2016-09-13 12:55
Thanks, I will check it soon. I never checked it with Empathy.
If the Debug interface works for you, then the debug log would be very appriciated.
Does Empathy show Debug info right on the connection manager started or it waits for connection to be established (which is the case for current version of KDE Telepathy Debugger)?

**Comment by Kaffeine** [comment] 2016-09-13 13:33
OK, I have the same issue.
I think it is after https://github.com/Kaffeine/telegram-qt/commit/1967d6a37668bc02c6651cdb207c60c4a67e02a0 or https://github.com/Kaffeine/telegram-qt/commit/5a10fcb6786636aaf13f7587ce807dfca5323c85. I tested new authorization with telegram-qt/testApp after the commits, but may be Morse works differently.

**Comment by Kaffeine** [comment] 2016-09-13 14:04
I found why my test succeed.

Time ago I introduced [built-in list of servers](https://github.com/Kaffeine/telegram-qt/blob/master/telegram-qt/CTelegramDispatcher.cpp#L42) and it seems that I made a typo in the first server, because 1) the server doesn't answer, 2) morse has a [similar address](https://github.com/TelepathyQt/telepathy-morse/blob/master/connection.cpp#L267).
All together: because of the typo in telegram server list, I got connection to the appropriate DC and had no "PHONE_MIGRATE_2" error, which I now have with Morse, which successfully connects to the first server.

So the fix has three steps:
1) Update builtInDc list in TelegramQt.
2) Remove DC override from Morse (actually we need to add an account option to set the DC ip)
3) Fixup phone code requests migration.

**Comment by Kaffeine** [comment] 2016-09-13 14:52
Fixed by https://github.com/Kaffeine/telegram-qt/commit/bdaf7bd6eac0d08b3c65347efef42761c6c5bc86, the bad commit is https://github.com/Kaffeine/telegram-qt/commit/1967d6a37668bc02c6651cdb207c60c4a67e02a0

@ItachiSan: You need to update only TelegramQt to get this fixed.
Sadly I think that I found yet another issue. Avatars are (mostly) missing for me.
Seems to be a regression in TelegramQt again. I'm working hard to release this, so I reworked some parts to be future-proof and compatible with further updates. The reworks leads to regressions. Sorry.

**Closed as completed by Kaffeine** 2016-09-13 14:52 UTC
Labels: Bug, In Progress
