### ISSUE TITLE
Read notification send own message back

### ISSUE THREAD

**Issue by nod0n** [TelepathyQt/telepathy-morse#47] opened 2017-06-06 13:21 UTC
Hello
When my chat partner reads the message I written to him, I get the message I did send to him back as normal message. It's like every time he reads one of my messages, he would send me the exact same message back.
I'm running KDE-Neon User Edition. So my KDE Packages should be pretty up to date.
Salutations Nod0n

**Comment by ghost** [comment] 2017-06-06 18:00
This issue is fixed in master, maybe KDE neon is building the released version for it's User Edition packages.  Kaffeine, would it be possible to make a release with the fix included? 0.1.1 maybe?

**Comment by Kaffeine** [comment] 2017-06-06 21:24
Sadly, I have almost no time this week, but I will go to check the version in KDE Neon to close the issue.

>Kaffeine, would it be possible to make a release with the fix included? 0.1.1 maybe?

For three month I'm planning to release 0.2.0, but I consider channel (mega/super groups) support as a crucial feature for the nearest release. It can be finished in five hours, but I don't have them yet.
I'm sure that I'll do the 0.2.0 release this month.

**Comment by Kaffeine** [comment] 2017-06-07 08:57
@nod0n ,
>I'm running KDE-Neon User Edition

>https://neon.kde.org/download: (User Edition) Featuring the latest officially released KDE software on a stable base.

As CliffordD already said, the issue is solved in master (by b092650210df28eba58c2ff4c72880bd0c0f0045 and also a lot of commits in the telegram-qt library) and there was not a 'stable' release yet.

**Comment by Kaffeine** [comment] 2017-06-13 10:50
Duplicates #42

**Closed as completed by Kaffeine** 2017-06-13 10:50 UTC
Labels: duplicate

**Comment by nod0n** [comment] 2017-06-13 14:18
Thx for all the informations. It's good to hear, that is has already been fixed and will come to KDE-Neon in the future.
Thx!
